### ISSUE TITLE
Connect Fonts version change

### ISSUE THREAD

**Issue by adamlazar1** [autopkg/markkenny-recipes#2]
Version 26.0.0 is out with Sequoia support.

New URL is:
https://sparkle.extensis.com/u/ST/EN/suitcase26en.xml

Existing URL in recipe:
Process:

Processor: SparkleUpdateInfoProvider
Arguments:
appcast_url: https://sparkle.extensis.com/u/ST/EN/suitcase25en.xml

**Comment by markkenny** [comment]
Updated this one too. Thanks

**Comment by markkenny** [comment]
Updated sparkle URL
